### ISSUE TITLE
ModelOutputv2.rmd has hard-coded path parameters

### ISSUE THREAD

**Issue by acmoody** [kendrakaiser/WRWC#5]
The end of `run_models.r` saves relevant path information in the file rmd_params_list.rdata, but this does not appear to be loaded in by `ModelOutputv2.rmd`

**Comment by kendrakaiser** [comment]
I haven't found a way to load a saved set of params into the yaml section at the top, and loading in the body of the .Rmd gives you an error "cannot change value of locked biding for 'params'" because it is read only.

I saved them hoping there could be a work around for the fact that I keep having problems with render, which is the most ideal way to do it, but keeps giving me errors, particularly `! Missing endcsname inserted`

I did find hard coded file paths in the first section of the Rmd though and fixed those

**Comment by kendrakaiser** [comment]
Fixed the issue - it was a relative versus direct path issue

**Comment by acmoody** [comment]
PDF creation is working from `run_models.r` now. Thanks!
